import { FilmType } from '../types/types';


export const catalogFilms: FilmType[] = [
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Adventure',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
];
