import { FilmType } from '../types/types';


export const catalogFilms: FilmType[] = [
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Comedies',
    released: 2005,
    id: 1,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    name: 'Gangs of new york',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/Gangs_of_New_York_Poster.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/gangs_of_new_york.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/gangs_of_new_york.jpg',
    backgroundColor: '#A6B7AC',
    description: 'In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father\'s killer.',
    rating: 8.8,
    scoresCount: 370881,
    director: 'Martin Scorsese',
    starring: ['Leonardo DiCaprio', 'Cameron Diaz', 'Daniel Day-Lewis'],
    runTime: 167,
    genre: 'Crime',
    released: 2002,
    id: 2,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    name: 'Pulp Fiction',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/Pulp_Fiction.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/pulp-fiction.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/Pulp_Fiction.jpg',
    backgroundColor: '#795433',
    description: 'The lives of two mob hitmen, a boxer, a gangster & his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    rating: 1.5,
    scoresCount: 1635992,
    director: 'Quentin Tarantino',
    starring: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    runTime: 153,
    genre: 'Documentary',
    released: 1994,
    id: 3,
    isFavorite: false,
    videoLink: 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  }, {
    name: 'What We Do in the Shadows',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/What-We-Do-in-the-Shadows.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/what-we-do-in-the-shadows.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/What-We-Do-in-the-Shadows.jpg',
    backgroundColor: '#A39E81',
    description: 'A look into the daily (or rather, nightly) lives of three vampires who\'ve lived together for over 100 years, in Staten Island.',
    rating: 7.2,
    scoresCount: 6173,
    director: 'Jemaine Clement',
    starring: ['Kayvan Novak', 'Matt Berry', 'Natasia Demetriou'],
    runTime: 30,
    genre: 'Comedy',
    released: 2019,
    id: 4,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/War_of_the_Worlds.jpg',
    name: 'War of the Worlds',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/war-of-the-worlds.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/War_of_the_Worlds.jpg',
    backgroundColor: '#9B7E61',
    description: 'As Earth is invaded by alien tripod fighting machines, one family fights for survival.',
    rating: 9.3,
    scoresCount: 386834,
    director: 'Steven Spielberg',
    starring: ['Tom Cruise', 'Dakota Fanning', 'Tim Robbins'],
    runTime: 116,
    genre: 'Horror',
    released: 2005,
    id: 5,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  },
  {
    name: 'Gangs of new york',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/Gangs_of_New_York_Poster.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/gangs_of_new_york.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/gangs_of_new_york.jpg',
    backgroundColor: '#A6B7AC',
    description: 'In 1862, Amsterdam Vallon returns to the Five Points area of New York City seeking revenge against Bill the Butcher, his father\'s killer.',
    rating: 8.8,
    scoresCount: 370881,
    director: 'Martin Scorsese',
    starring: ['Leonardo DiCaprio', 'Cameron Diaz', 'Daniel Day-Lewis'],
    runTime: 167,
    genre: 'Crime',
    released: 2002,
    id: 6,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    name: 'Pulp Fiction',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/Pulp_Fiction.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/pulp-fiction.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/Pulp_Fiction.jpg',
    backgroundColor: '#795433',
    description: 'The lives of two mob hitmen, a boxer, a gangster & his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    rating: 1.5,
    scoresCount: 1635992,
    director: 'Quentin Tarantino',
    starring: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    runTime: 153,
    genre: 'Crime',
    released: 1994,
    id: 7,
    isFavorite: false,
    videoLink: 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  }, {
    name: 'What We Do in the Shadows',
    posterImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/poster/What-We-Do-in-the-Shadows.jpg',
    previewImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/preview/what-we-do-in-the-shadows.jpg',
    backgroundImage: 'https://assets.htmlacademy.ru/intensives/javascript-3/film/background/What-We-Do-in-the-Shadows.jpg',
    backgroundColor: '#A39E81',
    description: 'A look into the daily (or rather, nightly) lives of three vampires who\'ve lived together for over 100 years, in Staten Island.',
    rating: 7.2,
    scoresCount: 6173,
    director: 'Jemaine Clement',
    starring: ['Kayvan Novak', 'Matt Berry', 'Natasia Demetriou'],
    runTime: 30,
    genre: 'Horror',
    released: 2019,
    id: 8,
    isFavorite: false,
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
    previewVideoLink: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
];
